apiVersion: v1
kind: Pod
metadata:
  name: pod-env-example
spec:
  containers:
    - name: app-container
      image: busybox
      command: ["sh", "-c", "echo DB_HOST=$DB_HOST && echo DB_PORT=$DB_PORT && sleep 3600"]
      envFrom:
        - configMapRef:
            name: db-config
