apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo
  labels:
    app: sidecar-example
spec:
  containers:
  - name: main-app
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - while true;
        do echo "Hello from the main app at $(date)" >> /var/log/app.log;
        sleep 5;
        done
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log

  - name: sidecar-logger
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - tail -f /var/log/app.log
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log

  volumes:
  - name: shared-logs
    emptyDir: {}

